### ISSUE TITLE
Possibility for downloading only one size per picture?

### ISSUE THREAD

**Issue by gernd** [masneyb/flickrdownload#13]
I use flickrdownload to save all my flickr images into a dedicated folder and then use them as random source for my screensaver.

Therefore it would be sufficient for me to only have one size per picture and not thumbnails etc.

Is there a possibility to achieve this?

**Comment by horsepunchkid** [comment]
I created a pull request [https://github.com/masneyb/flickrdownload/pull/14] to implement this feature. I've tested it on my own account to confirm that it works as I'd expect.

**Comment by masneyb** [comment]
I merged that pull request into master.
