### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by shokk** [masneyb/flickrdownload#15]
It seems flags like --onlyOriginals are not included in the 0.8 binaries
Can you add instructions for how this should be built? I see that .project is related to eclipse, but is that necessary or can I do something like a "make; make install" style steps for java? Barring all that, can new binaries be posted?

**Comment by horsepunchkid** [comment]
If you have Apache Ant installed, you can build the project just by running `ant` with no arguments from within the project directory. I added a binary here [https://github.com/horsepunchkid/flickrdownload/tree/master/binaries], but please don't take it as official. @masneyb, I gave my branch a version bump, if you want to pull that, but of course don't feel obliged. Let me know if you'd like me to take the binary down.

**Comment by shokk** [comment]
Thanks I will give this a shot

**Comment by shokk** [comment]
Yeah this worked.
