### ISSUE TITLE
During --limitToSet, thumbnails for all sets are downloaded

### ISSUE THREAD

**Issue by horsepunchkid** [masneyb/flickrdownload#6]
This is a somewhat minor issue and arguably a non-issue, but I figured I would bring it up and see if we can find a solution. My experience is that I often want to download just one set of a dozen or two photos, but with a hundred or so total sets, it spends more time downloading set thumbnails than actually downloading the one set's photos and data.

If it were to simply not download the thumbnails, you would have a lot of broken images on the collections.html page. This might be acceptable, since the links on that page to the sets are invalid, anyway.

A better solution might be to only download thumbnails for collections that the set is part of, and only include those collections on the page.

**Comment by masneyb** [comment]
I am closing this ticket since the patch from @horsepunchkid has been merged in.

Brian
